server:
  port: 8080

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/blog_application
    password: ayush@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


